

# Basic training

---
random_seed: 42
ckpt_path: null
gpus: "0,1"

# Dataset options:
dataset:
  root_path: "/project/shrikann_35/nmehlman/vpc"
  system: "T10-2"
  split: "libri_dev_trials_f"

# Dataloader options:
dataloader:
  batch_size: 64
  num_workers: 8
  train_frac: 0.8

# Model options:
lightning:
  hparams: 
    num_tokens: 28
    embedding_dim: 128
    num_layers: 2
    dropout: 0.0
  optimizer_params:
    lr: 0.001


# Training options:
trainer:
  max_epochs: 1
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/home1/nmehlman/arts_vpc/logs/tensorboard"
  name: "debug_gpu"
  version: null     # Automatic versioning if set to null (recommended)


