

# Speaker Verification Evaluation

---

ckpt_path: "/home1/nmehlman/arts_vpc/logs/tensorboard/main_fit/version_0/checkpoints/epoch=11-step=54600.ckpt"
output_dir: "/project/shrikann_35/nmehlman/vpc/embeds/"
  
# Dataset options:
dataset:
  root_path: "/project/shrikann_35/nmehlman/vpc"

# Dataloader options:
dataloader:
  batch_size: 128
  num_workers: 4
  train_frac: 1.0
