

# Speaker Verification Evaluation

---

ckpt_path: "/home1/nmehlman/arts_vpc/logs/tensorboard/main_fit/version_8/checkpoints/epoch=0-step=4550.ckpt"
output_dir: "/project/shrikann_35/nmehlman/vpc/embeds/"
  
# Dataset options:
dataset:
  root_path: "/project/shrikann_35/nmehlman/vpc"
  system: "B4"

# Dataloader options:
dataloader:
  batch_size: 128
  num_workers: 0
  train_frac: 1.0
