

# Basic training

---
random_seed: 42
ckpt_path: null
gpus: "0,1"

# Dataset options:
dataset:
  root_path: "/project/shrikann_35/nmehlman/vpc"
  system: "all"
  split: "train-clean-360"

# Dataloader options:
dataloader:
  batch_size: 64
  num_workers: 4
  train_frac: 0.8

# Model options:
lightning:
  hparams: 
    num_tokens: 28
    embedding_dim: 32
    num_layers: 1
    dropout: 0.25
  optimizer_params:
    lr: 0.001
    weight_decay: 0.0001
  scheduler_params:
    T_max: 500
    eta_min: 0.000001


# Training options:
trainer:
  max_epochs: 500
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/home1/nmehlman/arts_vpc/logs/tensorboard"
  name: "test_on_all_systems"
  version: null     # Automatic versioning if set to null (recommended)


