name: Python Compatibility Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
          python-version: ${{ matrix.python-version }}

      - name: Check if lockfile is up to date
        run: uv lock --check

      - name: Install the project
        run: uv sync --all-extras

      - name: Test import
        run: |
          uv run python -c "import whisperx; print('Successfully imported whisperx')"
