

# Speaker Verification Evaluation

---
eval:
  ckpt_path: "/home1/nmehlman/arts_vpc/logs/tensorboard/first_train/version_3/checkpoints/epoch=499-step=3500.ckpt"
  device: "cpu"
  enroll_embed_dir: "/project/shrikann_35/nmehlman/vpc/T10-2/data/libri_dev_enrolls_T10-2/embeds"
  test_embed_dir: "/project/shrikann_35/nmehlman/vpc/T10-2/data/libri_dev_trials_f_T10-2/embeds"

# Dataset options:
enroll_dataset:
  root_path: "/project/shrikann_35/nmehlman/vpc"
  system: "T10-2"
  split: "libri_dev_enrolls_T10-2"

test_dataset:
  root_path: "/project/shrikann_35/nmehlman/vpc"
  system: "T10-2"
  split: "libri_dev_trials_f_T10-2"

# Dataloader options:
dataloader:
  batch_size: 64
  num_workers: 4
  train_frac: 1.0
